# Generated by Django 3.1.2 on 2022-01-12 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('foto', models.ImageField(upload_to='photos/', verbose_name='foto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, verbose_name='dni')),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=60, verbose_name='apellidos')),
                ('direccion', models.CharField(max_length=150, verbose_name='direccion')),
                ('fechaNacimiento', models.DateField(verbose_name='fechaNacimiento')),
                ('fechaAlta', models.DateField(verbose_name='fechaAlta')),
                ('activo', models.BooleanField(verbose_name='activo')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9, verbose_name='dni')),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=60, verbose_name='apellidos')),
                ('direccion', models.CharField(max_length=150, verbose_name='direccion')),
                ('biografia', models.CharField(max_length=255, verbose_name='biografia')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='username')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='titulo')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('nivel', models.IntegerField(verbose_name='nivel')),
                ('fechaInicio', models.DateField(verbose_name='fechaInicio')),
                ('fechaFin', models.DateField(verbose_name='fechaFin')),
                ('informeFinal', models.CharField(max_length=255, verbose_name='informeFinal')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='nucleo.categoria', verbose_name='idCategoria')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='nucleo.empleado', verbose_name='idEmpleado')),
            ],
        ),
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInscripcion', models.DateField(verbose_name='fechaInscripcion')),
                ('rol', models.CharField(max_length=100, verbose_name='rol')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='nucleo.cliente', verbose_name='idCliente')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='nucleo.proyecto', verbose_name='idProyecto')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.usuario', verbose_name='idUsuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nucleo.usuario', verbose_name='idUsuario'),
        ),
    ]
