# Generated by Django 3.1.2 on 2022-01-28 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_auto_20220127_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='participa',
            name='fechaInscripcion',
            field=models.DateField(verbose_name='Fecha de inscripción'),
        ),
        migrations.AlterField(
            model_name='participa',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='participa',
            name='rol',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rol'),
        ),
    ]

    