# Generated by Django 3.1.2 on 2022-02-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20220128_1202'),
        ('project', '0003_auto_20220127_1802'),
    ]

    operations = [
    ]