# Generated by Django 3.1.2 on 2022-02-03 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
        ('project', '0006_merge_20220202_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participa',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='participa',
            name='rol',
            field=models.CharField(choices=[('Sin ningún rol asignado', 'Sin ningún rol asignado'), ('Desarrollo en Back-End', 'Desarrollo en Back-End'), ('Desarrollo en Front-End', 'Desarrollo en Front-End'), ('Desarollo completo en las areas de programación', 'Desarollo completo en las areas de programación')], default='Sin ningún rol asignado', max_length=100, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='project',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='category.category', verbose_name='Categoría asociada'),
        ),
        migrations.AlterField(
            model_name='project',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Descripción del Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL, verbose_name='Empleado destinado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fechaFin',
            field=models.DateField(verbose_name='Fecha de Fin del Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fechaInicio',
            field=models.DateField(verbose_name='Fecha de Inicio del proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='informeFinal',
            field=models.CharField(max_length=255, verbose_name='Informe Final del Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título del Proyecto'),
        ),
    ]
