# Generated by Django 3.1.2 on 2022-01-09 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fechaAlta',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nombre',
        ),
    ]
