# Generated by Django 3.1.2 on 2022-01-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_client',
        ),
        migrations.AddField(
            model_name='user',
            name='role_user',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Empleado', 'Empleado'), ('Administrador', 'Administrador')], default='Cliente', max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='apellidos',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='biografia',
            field=models.CharField(max_length=400, null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(max_length=9, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fechaAlta',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fechaNacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
    